import type {
  AchievementCode,
  AchievementDefinition,
  AchievementTier,
} from "./types";

const tierPoints: Record<AchievementTier, number> = {
  bronze: 10,
  silver: 20,
  gold: 40,
  special: 60,
};

function define(
  input: Omit<AchievementDefinition, "points" | "titleKey" | "descriptionKey">,
): AchievementDefinition {
  return {
    ...input,
    points: tierPoints[input.tier],
    titleKey: `achievements.items.${input.code}.title`,
    descriptionKey: `achievements.items.${input.code}.description`,
  };
}

export const achievementDefinitions: AchievementDefinition[] = [
  define({
    code: "first_sync",
    category: "activation",
    tier: "bronze",
    iconKey: "rocket",
    order: 10,
  }),
  define({
    code: "sessions_1",
    category: "activation",
    tier: "bronze",
    iconKey: "messages-square",
    order: 20,
  }),
  define({
    code: "streak_3",
    category: "consistency",
    tier: "bronze",
    iconKey: "flame",
    order: 50,
  }),
  define({
    code: "streak_7",
    category: "consistency",
    tier: "silver",
    iconKey: "flame",
    order: 60,
  }),
  define({
    code: "streak_14",
    category: "consistency",
    tier: "gold",
    iconKey: "flame",
    order: 70,
  }),
  define({
    code: "streak_30",
    category: "consistency",
    tier: "gold",
    iconKey: "flame",
    order: 80,
  }),
  define({
    code: "active_days_7",
    category: "consistency",
    tier: "bronze",
    iconKey: "calendar-check",
    order: 90,
  }),
  define({
    code: "active_days_30",
    category: "consistency",
    tier: "silver",
    iconKey: "calendar-check",
    order: 100,
  }),
  define({
    code: "active_days_100",
    category: "consistency",
    tier: "gold",
    iconKey: "calendar-check",
    order: 110,
  }),
  define({
    code: "active_days_365",
    category: "consistency",
    tier: "special",
    iconKey: "calendar-check",
    order: 120,
  }),
  define({
    code: "sessions_200",
    category: "volume",
    tier: "bronze",
    iconKey: "messages-square",
    order: 130,
  }),
  define({
    code: "sessions_1k",
    category: "volume",
    tier: "silver",
    iconKey: "messages-square",
    order: 131,
  }),
  define({
    code: "sessions_5k",
    category: "volume",
    tier: "gold",
    iconKey: "messages-square",
    order: 132,
  }),
  define({
    code: "sessions_20k",
    category: "volume",
    tier: "gold",
    iconKey: "messages-square",
    order: 133,
  }),
  define({
    code: "sessions_100k",
    category: "volume",
    tier: "special",
    iconKey: "messages-square",
    order: 134,
  }),
  define({
    code: "spend_usd_100",
    category: "spend",
    tier: "bronze",
    iconKey: "coins",
    order: 135,
  }),
  define({
    code: "spend_usd_1k",
    category: "spend",
    tier: "silver",
    iconKey: "coins",
    order: 136,
  }),
  define({
    code: "spend_usd_5k",
    category: "spend",
    tier: "gold",
    iconKey: "coins",
    order: 137,
  }),
  define({
    code: "spend_usd_20k",
    category: "spend",
    tier: "gold",
    iconKey: "coins",
    order: 138,
  }),
  define({
    code: "spend_usd_100k",
    category: "spend",
    tier: "special",
    iconKey: "coins",
    order: 139,
  }),
  define({
    code: "tokens_100k",
    category: "volume",
    tier: "bronze",
    iconKey: "coins",
    order: 140,
  }),
  define({
    code: "tokens_1m",
    category: "volume",
    tier: "silver",
    iconKey: "coins",
    order: 141,
  }),
  define({
    code: "tokens_10m",
    category: "volume",
    tier: "gold",
    iconKey: "coins",
    order: 142,
  }),
  define({
    code: "tokens_1b",
    category: "volume",
    tier: "gold",
    iconKey: "coins",
    order: 143,
  }),
  define({
    code: "tokens_10b",
    category: "volume",
    tier: "special",
    iconKey: "coins",
    order: 144,
  }),
  define({
    code: "tokens_100b",
    category: "volume",
    tier: "special",
    iconKey: "coins",
    order: 145,
  }),
  define({
    code: "active_hours_10",
    category: "volume",
    tier: "bronze",
    iconKey: "clock",
    order: 146,
  }),
  define({
    code: "active_hours_100",
    category: "volume",
    tier: "silver",
    iconKey: "clock",
    order: 147,
  }),
  define({
    code: "active_hours_200",
    category: "volume",
    tier: "gold",
    iconKey: "clock",
    order: 148,
  }),
  define({
    code: "active_hours_500",
    category: "volume",
    tier: "special",
    iconKey: "clock",
    order: 149,
  }),
  define({
    code: "active_hours_2000",
    category: "volume",
    tier: "special",
    iconKey: "clock",
    order: 150,
  }),
  define({
    code: "reasoning_25",
    category: "craft",
    tier: "special",
    iconKey: "brain",
    order: 250,
  }),
  define({
    code: "reasoning_40",
    category: "craft",
    tier: "special",
    iconKey: "brain",
    order: 260,
  }),
  define({
    code: "cache_15",
    category: "craft",
    tier: "special",
    iconKey: "database-zap",
    order: 270,
  }),
  define({
    code: "cache_30",
    category: "craft",
    tier: "special",
    iconKey: "database-zap",
    order: 280,
  }),
  define({
    code: "project_focus_70",
    category: "craft",
    tier: "special",
    iconKey: "focus",
    order: 290,
  }),
  define({
    code: "project_focus_90",
    category: "craft",
    tier: "special",
    iconKey: "focus",
    order: 300,
  }),
  define({
    code: "models_3",
    category: "exploration",
    tier: "bronze",
    iconKey: "orbit",
    order: 310,
  }),
  define({
    code: "models_5",
    category: "exploration",
    tier: "silver",
    iconKey: "orbit",
    order: 320,
  }),
  define({
    code: "tools_2",
    category: "exploration",
    tier: "bronze",
    iconKey: "wrench",
    order: 330,
  }),
  define({
    code: "tools_4",
    category: "exploration",
    tier: "silver",
    iconKey: "wrench",
    order: 340,
  }),
  define({
    code: "projects_5",
    category: "exploration",
    tier: "silver",
    iconKey: "folder-git",
    order: 350,
  }),
  define({
    code: "projects_15",
    category: "exploration",
    tier: "gold",
    iconKey: "folder-git",
    order: 360,
  }),
  define({
    code: "devices_2",
    category: "exploration",
    tier: "silver",
    iconKey: "monitor-smartphone",
    order: 370,
  }),
  define({
    code: "devices_3",
    category: "exploration",
    tier: "gold",
    iconKey: "monitor-smartphone",
    order: 380,
  }),
  define({
    code: "first_follow",
    category: "social",
    tier: "bronze",
    iconKey: "user-plus",
    order: 390,
  }),
  define({
    code: "following_10",
    category: "social",
    tier: "silver",
    iconKey: "user-plus",
    order: 400,
  }),
  define({
    code: "first_follower",
    category: "social",
    tier: "silver",
    iconKey: "heart-handshake",
    order: 410,
  }),
  define({
    code: "followers_10",
    category: "social",
    tier: "gold",
    iconKey: "heart-handshake",
    order: 420,
  }),
  define({
    code: "mutual_3",
    category: "social",
    tier: "gold",
    iconKey: "users",
    order: 430,
  }),
  define({
    code: "mutual_10",
    category: "social",
    tier: "special",
    iconKey: "users",
    order: 440,
  }),
  define({
    code: "leaderboard_day_top50",
    category: "leaderboard",
    tier: "bronze",
    iconKey: "target",
    order: 450,
  }),
  define({
    code: "leaderboard_week_top50",
    category: "leaderboard",
    tier: "silver",
    iconKey: "trophy",
    order: 460,
  }),
  define({
    code: "leaderboard_month_top50",
    category: "leaderboard",
    tier: "silver",
    iconKey: "trophy",
    order: 470,
  }),
  define({
    code: "leaderboard_all_time_top100",
    category: "leaderboard",
    tier: "gold",
    iconKey: "trophy",
    order: 480,
  }),
  define({
    code: "leaderboard_all_time_top10",
    category: "leaderboard",
    tier: "special",
    iconKey: "trophy",
    order: 490,
  }),
  define({
    code: "leaderboard_all_time_first",
    category: "leaderboard",
    tier: "special",
    iconKey: "sparkles",
    order: 500,
  }),
];

export const achievementDefinitionMap = new Map<
  AchievementCode,
  AchievementDefinition
>(achievementDefinitions.map((definition) => [definition.code, definition]));
