import type { Metadata } from "next";
import { cookies } from "next/headers";
import Script from "next/script";
import { getLocale } from "next-intl/server";
import { ClarityInit } from "@/components/providers/clarity-init";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ThemeScript } from "@/components/providers/theme-script";
import { TooltipProvider } from "@/components/ui/tooltip";
import { defaultLocale } from "@/lib/i18n";
import { getThemeMode, themeCookieName } from "@/lib/theme";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gaSecret = process.env.GA_SECRET;
  const clarityId = process.env.CLARITY_ID?.trim();
  const cookieStore = await cookies();
  const locale =
    (await getLocale().catch(() => defaultLocale)) ?? defaultLocale;
  const initialThemeMode = getThemeMode(
    cookieStore.get(themeCookieName)?.value,
  );

  return (
    <html lang={locale} suppressHydrationWarning className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <ThemeScript initialThemeMode={initialThemeMode} />
        {gaSecret ? (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${gaSecret}`}
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '${gaSecret}');`}
            </Script>
          </>
        ) : null}
        {clarityId ? <ClarityInit projectId={clarityId} /> : null}
        <ThemeProvider initialThemeMode={initialThemeMode}>
          <TooltipProvider>{children}</TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
