-- Compatibility placeholder.
-- The auth baseline was moved to an earlier migration timestamp so fresh installs
-- create auth tables before usage tables. Keep this migration name as a no-op so
-- existing local databases that already recorded it in _prisma_migrations do not
-- lose the historical entry.
